require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split('.').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '255611425468',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'Alison',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'off',
    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'off',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'off',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
   ALIVE_URL: process.env.ALIVE_URL,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU05LaVJIWGJodk55V0diT0Ztblc0VWFicUIrdjdObmFscE9hTWkxM20xYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVEtiaWlHcklrVFBhVFVMWHREY3MwMm9Zc1dSQjR5TzVPREVJa3FQUkpFaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvRlY2MXM2VGlEYUJ2b1JSVlFXVmhuY25xWkRpNXJZY291T3B0QkNvdDJNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3SXBiY3h2MlhFQ2RIM3pEb01OUTZ0TWlnRUxBTndyZFZoSmNTOG9TK3dVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1BSTl1QkI0ekxjZFVXS20wSlRkN0dLY2t2Q2tHRWFHL3BBYVZsYWs4bW89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlEvckEyN1RXT3ZLTXF1SmZ1cURweXY5Rkl2aFRQWWVPN1JqL2Rja1JnUzg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaURaY0VpN0dVWkVHay9SU05VdDBtREFxOHF1WGk3WXFjQ2ZjNFRQempsRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMmg0Y01HUE9zYTFId0xINHQ3L2hUQUJKNmNNUTljcWthQlpjdkVWSUJsQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkRCRGFxYnc5UFZKOHdDWnZrNW0rNk9QMGdDOTZrU2lDS1VpYzhDZ2tsLzAraXFJZHdqQkphcWxkeDZ5TnpYOGZRdWFNZnpVWENDT0dOeXN6K1J2U0JBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MSwiYWR2U2VjcmV0S2V5IjoiWnV5N01UTk41VERjQnJFTDhrSE0xOU1lVWUycUpZWHllM2JDSlk2NVFwND0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOlt7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTU2MTE0MjU0NjhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiOTJFQzY5MDU2NzNDRkM3MUVFQjhEMTMyNTA4MkIzNkEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0OTk3OTE4NH0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU1NjExNDI1NDY4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjAzMkQxNTU3RUJBODMyRTBEMjA4NEIxRTVCREM3RDMwIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDk5NzkxODV9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IjVTRjRHWDM0IiwibWUiOnsiaWQiOiIyNTU2MTE0MjU0Njg6NDJAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiYWxpc29uIiwibGlkIjoiODUxNzU1NzY5MDU0Mzo0MkBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ05MeTJQVUZFSkdndXNJR0dBOGdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6InljTm5ieE9FaWgxcm5RZTlRbThpQlluT2dWY1FGRVVLSWtoL25lR2JObnM9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImtkYlVtSVFUREkrRXBxbkFOcGdiSVJYWUIxWDdtYVRCdVg1TXNMNlUxYXlRYVpkd01XaGpHSzdJTWovZ0RBcGMycit6UUJLcEoxQ2RrTVZ6U1ZlbkRnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJoMEVha2U0U3BLSEppK3kvR1Z0c1hhVU1JYUNDY1RRRWdJdXByMzBaM3Vzc0xNd0Z6ZjhUQ3FVeStWVklwYXNVVmVPRGhtWjl4S2RENVgxZUwvdzNCQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NTYxMTQyNTQ2ODo0MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJjbkRaMjhUaElvZGE1MEh2VUp2SWdXSnpvRlhFQlJGQ2lKSWY1M2htelo3In19XSwicGxhdGZvcm0iOiJzbWJhIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQWdJQWc9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NDk5NzkxNjcsImxhc3RQcm9wSGFzaCI6IjJQMVloZiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBR0V4In0=',
    timezone: 'Africa/Nairobi',
    USER_LID: process.env.YOUR_LID || null,
    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'paused'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'paused'),

    mapPresence
};
